### ISSUE TITLE
getMainWindow fails in VS 2017 Version 15.5.7

### ISSUE THREAD

**Issue by ki82** [Roemer/FlaUI#148]
I upgrade my VS 2017 to 15.5.7 and then our testcase that worked before with FlaUI stopped working.

```
var app = Application.Launch(applicationPath);

            using (var automation = new UIA3Automation())  {
                ...
                var loginWindow = app.GetMainWindow(automation);
                ...

```

Is there a workaround for getting the mainwindow in 15.5.7 with some other method?

More info about the error:

Test Name:	LoginTest
Test FullName:	AutoTest.Tests.LoginTest
Test Source:	C:\windows-client\UITest\FlaUI.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:02.9715237

Result StackTrace:	
at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at FlaUI.Core.Application.<WaitWhileMainHandleIsMissing>b__29_0()
   at FlaUI.Core.Tools.Retry.While(Func`1 whilePredicate, TimeSpan timeout, Nullable`1 retryInterval)
   at FlaUI.Core.Application.WaitWhileMainHandleIsMissing(Nullable`1 waitTimeout)
   at FlaUI.Core.Application.GetMainWindow(AutomationBase automation, Nullable`1 waitTimeout)
   at AutoTest.Tests.LoginTest() in C:\windows-client\UITest\FlaUI.cs:line 29
Result Message:	
Test method AutoTest.Tests.LoginTest threw exception: 
System.InvalidOperationException: Process has exited, so the requested information is not available.
Result StandardOutput:	C:\windows-client\bin\x64\Debug\flaui\..\app

**Comment by Roemer** [comment]
What application are you testing? It seems rather strange that this is an Visual Studio problem. What makes me suspicious is the message `Process has exited`. Can you check that you hare in the right process and that it is still running?

**Comment by Roemer** [comment]
Closed due to inactivity, please re-open if you can provide more information.

**Comment by stofte** [comment]
I'm seeing this issue when using VS2017. The "test" is basically the sample from the Wpf project. After seeing this exception, I noticed that the wpf EXE that's in the test projects output folder cannot be launched. There's no error, but the Event Log contains the following:

    Exception Info: System.Windows.Markup.XamlParseException
       at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
       at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
       at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
       at System.Windows.Application.LoadComponent(System.Object, System.Uri)
       at AzureDashboard.App.InitializeComponent()
       at AzureDashboard.App.Main()

The app itself launches fine from double-clicked from the Wpf projects output folder. Presumably this is "merely" a publishing issue. That WPF just silently fails is unfortunate, but not really FlaUI's fault.

**Comment by sweta553322** [comment]
@Roemer  I also face the same issue. While open the visual studio 2017 first time on windows 10 and run the flaui automation everything working as expected but due to some error if Automation failed and than if I re run the test than 

**var loginWindow = app.GetMainWindow(automation);**

Failed to locate the window.

I have to close all the visual studio running instance and than i have to start again.
I installed V2.0.0.0 rc from nuget .

let me know if you required more information

Kindly help me on this.
