### ISSUE TITLE
Build Server - Could not send mouse input. ErrorCode: 5

### ISSUE THREAD

**Issue by Sl1ckR1ck** [Roemer/FlaUI#204]
Hi,
i have wrote a bunch of UI tests which are working perfectly locally.

I now tried to setup an build to run those UITests on the build machine on demand.

The build agent have been setup properly to be able to run UI tests.

The problem is that when running those tests without connected using remote desktop connection any test with click actions fails. Any tests without click actions works.

If i leave my RDC session to the agent opened it works fine.
(When i minimize the RDC session, i get the errors too).

Not sure if the issue is related with FlaUI ?

Am i missing something?

**Comment by Sl1ckR1ck** [comment]
Thanks Roemer, ill try to change my Build configuration to follow the FAQ

**Comment by Sl1ckR1ck** [comment]
Just another quick question. I tried using the UIA automation instead, seems to work well for buttons (using .Invoke, but for TabItems i tried using .IsSelected=True and .Select and both return an exception:

FlaUI.Core.Exceptions.PatternNotSupportedException: The requested pattern 'SelectionItem [#10010]' is not supported ---> System.InvalidOperationException: Native pattern is null
Stack Trace:
at FlaUI.Core.FrameworkAutomationElementBase.GetNativePattern[T](PatternId pattern)
--- End of inner exception stack trace ---
at FlaUI.Core.FrameworkAutomationElementBase.GetNativePattern[T](PatternId pattern)

Is that how you interact with tabitem?
