### ISSUE TITLE
GetMainWindow in FLAUI gives error message UIA TimeOut , and launchs application multiple times

### ISSUE THREAD

**Issue by shekharss3** [Roemer/FlaUI#219]
I am into a weired problem. I amtrying to launch a window wpplication. It works well when i debug the autmated UI tests. When i run UI tests i get an error message when i try to launch the same window. 
The error mesage is as follows:

[Failed because: 
System.TimeoutException: UIA Timeout--->
  System.RunTime.InteropServices.COMException: Operation timed out. (exception from HESULT: 0*80131505)
  at 
  Interop .UIAutomationClient.CUIAutomation8Class.ElementFromHandle(Intptr hwnd)
  at FLaUI.UIUA3.UIA3Automation.<>_DisplayClass17.0.<FromHandle>b_0()
  at FLaUI.Core.Tools.Com.Call[T](Func1 nativeAction)
  --End of Inner exception stack trace---
    at at FLaUI.Core.Tools.Com.Call[T](Func1 nativeAction)
    at FLaUI.UIUA3.UIA3Automation.FromHandle(IntPtr hwnd)
    at FLAUI.Core.Application.GetMainWindow(AutomationBase automation, Nullable 1 wait Timeout)
    at 
    AutomationTestFramework.Classes.ApplicationLauncher.GetPTOApplicationLanched() in 
      ApplicationLauncher.cs ](url)
    
  And my GetPTOApplicationLanched() is :
 [private static Window GetPTOApplicationLanched()
        {
            try
            {
                using (var automation = new UIA3Automation())
                {
                    string path = ConfigurationManager.AppSettings["PTOPath"];
                    appPTO = FlaUI.Core.Application.Launch(path);
                    getPTOInstance = appPTO.GetMainWindow(automation, new TimeSpan(0, 30, 0));
                }
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show("Failed because :" + ex.ToString());
            }
            return getPTOInstance;
        }](url)

The problem is it first gives this error message then it again launches the application 3 times or soemtimes 2 times. And samething if i debug then it works well (only once launched). What could be the issue  ?

**Comment by Roemer** [comment]
Maybe your application hangs on lauch which also blocks the COM interop?
Have a look at `TransactionTimeout` and / or `ConnectionTimeout` from `UIA3Automation` and try to increase them.
