### ISSUE TITLE
 ItemRealizer.RealizeItems throws invalid operation exception

### ISSUE THREAD

**Issue by kevinheyvaert** [Roemer/FlaUI#256]
Sometimes (10 % of my run on CI) when I try to load all items in a automation element with the ItemRealizer, it throws with the following exception: 

`System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Interop.UIAutomationClient.IUIAutomationScrollPattern.SetScrollPercent(Double horizontalPercent, Double verticalPercent)
   at FlaUI.UIA3.Patterns.ScrollPattern.<>c__DisplayClass9_0.<SetScrollPercent>b__0()
   at FlaUI.Core.Tools.Com.Call(Action nativeAction)
   at FlaUI.UIA3.Patterns.ScrollPattern.SetScrollPercent(Double horizontalPercent, Double verticalPercent)
   at FlaUI.Core.Tools.ItemRealizer.RealizeItems(AutomationElement itemContainerElement)`

Is there a way to avoid this? I already used helper functions to wait with a timeout to check if the automation element is enabled and has the scroll pattern but does not help.

**Comment by Roemer** [comment]
Is there a chance that the CI sometimes runs the job with admin rights and sometimes without?

**Comment by kevinheyvaert** [comment]
@Roemer , CI has normally full admin rights and online 24/7 + no locked screen. So always in an active desktop session.

**Comment by Roemer** [comment]
Did you already increase the `TransactionTimeout` and `ConnectionTimeout` on the automation object?

**Comment by kevinheyvaert** [comment]
I have set them both to 3 seconds a couple of months. But sometimes I have still this issue

With increasing this values,  I also saw an increase of duration of testruns on CI on Windows 10 with our tests that implement FlaUI. Now the test run on CI with OS Win10 is around 50% longer in duration (45 min) as the one on Win7 (30 min). Not sure this is a known issue but I did not had the time yet to dig deeper into it.
