### ISSUE TITLE
ListBoxItem does not implement selection pattern

### ISSUE THREAD

**Issue by andyb1979** [Roemer/FlaUI#276]
Not sure if this is a bug, or my incorrect usage. I am using FLAUI 2.0.0 rc1. 

I am getting a ListBoxItem by AutomationID. it is returning correctly (not null) so I know I got the ListBoxItem. 

When I call .Select() on the ListBoxItem, I get an exception 
```
FlaUI.Core.Exceptions.PatternNotSupportedException : The requested pattern 'SelectionItem [#10010]' is not supported
  ----> System.InvalidOperationException : Native pattern is null
   at FlaUI.Core.FrameworkAutomationElementBase.GetNativePattern[T](PatternId pattern)
   at FlaUI.Core.AutomationPattern`2.get_Pattern()
   at FlaUI.Core.AutomationElements.PatternElements.SelectionItemAutomationElement.Select()
```

Inspecting the ListBoxItem none of the selection patterns are supported. What's the correct way to work with ListBoxItems ? 

Best regards, 
Andrew

**Comment by andyb1979** [comment]
I figured this one out. My ListBox was a custom control as per this issue here:
https://github.com/Roemer/FlaUI/issues/241

Once I reverted to standard ListBox, ListBoxItem, all works correctly.
