### ISSUE TITLE
'Value does not fall within the expected range' when accessing cached IsOffScreen

### ISSUE THREAD

**Issue by redsolo** [Roemer/FlaUI#48]
Im getting the below stack trace when I try to use caching of the IsOffScreen property.

My cache request looks like this:
```
var cacheRequest = new CacheRequest();
cacheRequest.Add(MainWindow.Automation.PropertyLibrary.Element.AutomationId);
cacheRequest.Add(MainWindow.Automation.PropertyLibrary.Element.IsOffscreen);
cacheRequest.Add(MainWindow.Automation.PatternLibrary.WindowPattern);
cacheRequest.TreeScope = TreeScope.Descendants;
using (cacheRequest.Activate())
{
    Window[] modalWindows = MainWindow.FindAllDescendants(cf => cf.ByControlType(ControlType.Window)).Select(ae => ae.AsWindow())
        .Where(w => w.Properties.IsOffscreen.ValueOrDefault).ToArray();
```

and the exception raised is:
```
Result StackTrace:	
at interop.UIAutomationCore.IUIAutomationElement.GetCachedPropertyValueEx(Int32 propertyId, Int32 ignoreDefaultValue)
   at FlaUI.Core.BasicAutomationElementBase.TryGetPropertyValue[T](PropertyId property, T& value)
   at FlaUI.Core.AutomationProperty`1.get_ValueOrDefault()
   at App.FunctionalTesting.App.<>c.<CheckForCrash>b__63_2(Window w) in C:\App.FunctionalTesting\App.cs:line 249
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at App.FunctionalTesting.App.CheckForCrash() in C:\App.FunctionalTesting\App.cs:line 248
   at App.FunctionalTestingTests.SampleTest.Test() in C:\App.FunctionalTestingTests\SampleTests.cs:line 28
Result Message:	System.ArgumentException : Value does not fall within the expected range.
```

**Comment by redsolo** [comment]
Closed as the TreeScope should be set to TreeScope.Element
