### ISSUE TITLE
Random operation time out Exception When finding elements with FindFirstByXpath

### ISSUE THREAD

**Issue by Davidacu** [Roemer/FlaUI#90]
To find elements I use this method a lot, is simple and I like it -> FindFirtByXpath
but Sometimes I get an exception, operation time out,
Any Idea on how to avoid this?

Operation timed out. (Exception from HRESULT: 0x80131505)System.Runtime.InteropServices.COMException (0x80131505): Operation timed out. (Exception from HRESULT: 0x80131505)
   at Interop.UIAutomationClient.IUIAutomationTreeWalker.GetNextSiblingElement(IUIAutomationElement element)
   at FlaUI.UIA3.UIA3TreeWalker.GetNextSibling(AutomationElement element)
   at FlaUI.Core.AutomationElementXPathNavigator.MoveToNext()
   at MS.Internal.Xml.XPath.XPathChildIterator.MoveNext()
   at MS.Internal.Xml.XPath.ChildrenQuery.Advance()
   at MS.Internal.Xml.XPath.ChildrenQuery.Advance()
   at MS.Internal.Xml.XPath.ChildrenQuery.Advance()
   at MS.Internal.Xml.XPath.FilterQuery.Advance()
   at MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext()
   at System.Xml.XPath.XPathNavigator.SelectSingleNode(XPathExpression expression)
   at System.Xml.XPath.XPathNavigator.SelectSingleNode(String xpath)
   at FlaUI.Core.AutomationElements.Infrastructure.AutomationElement.FindFirstByXPath(String xPath)

**Comment by Roemer** [comment]
Is the application under test not responding for some time or rebuilding the ui while you call FindFirstByXPath?

**Comment by Davidacu** [comment]
Yes, I found a method Helpers.WaitUntilResponsive()
Will that help?

**Comment by Roemer** [comment]
It would make sense to wait until your application is not blocking anymore before you search for elements. So you can try the wait method or any other method which tells you if the application has finished whatever it is doing 😆
As an alternative, I could extend the xpath mechanism with flags to retry on exceptions and timeouts.

**Comment by Davidacu** [comment]
using Helpers.WaitUntilResponsive(container) has helped.
But sometimes I get another exception :
System.Runtime.InteropServices.COMException (0x80040201): An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)
   at Interop.UIAutomationClient.IUIAutomationElement.GetCurrentPropertyValueEx(Int32 propertyId, Int32 ignoreDefaultValue)
   at FlaUI.UIA3.UIA3BasicAutomationElement.InternalGetPropertyValue(Int32 propertyId, Boolean cached, Boolean useDefaultIfNotSupported)
   at FlaUI.Core.BasicAutomationElementBase.TryGetPropertyValue[T](PropertyId property, T& value)
   at FlaUI.Core.Input.Helpers.WaitUntilResponsive(AutomationElement automationElement, TimeSpan timeout) 

Any idea on what could do in this case, I haven't found a lot on info on this exception.

**Comment by ArunaBalasubramanian** [comment]
Can you please suggest how to wait while the application is rebuilding the UI ?

**Comment by Roemer** [comment]
@ArunaBalasubramanian Whenever possible use async loading in your application with a spinner or some other kind of loading indicator and let FlaUI wait until that indicator is gone / hidden.

**Comment by ArunaBalasubramanian** [comment]
@Roemer Thanks for a quick response. Unfortunately, there are no such indicators in my application. 
I did try using wait until the element in the new page loaded is not null, but this appears flaky. I either end up in NullReferenceException or COMException - Operation Timeout.

Could you please suggest any other alternative?

**Comment by Roemer** [comment]
It is possible that FlaUI "blocks" while the application is loading (blocked) and therefore a COM timeout is fairly common. Could you put it in a retry loop and just retry on the com timeout exception?

**Comment by ArunaBalasubramanian** [comment]
Thanks @Roemer , that seems to have fixed my issue.

**Comment by Roemer** [comment]
I just implemented a `TransactionTimeout` on the Automation object which can be used to increase some UIA timeouts under the hood. You might also try that one. Note that this only works in UIA3.

**Comment by DavidKarlas** [comment]
I just want to point out, that it might make sense to also set `ConnectionTimeout` and `TransactionTimeout`. `TransactionTimeout` might not be enough.
